### ISSUE TITLE
US-NM: K-4553 - Rio Grande del Norte National Monument

### ISSUE THREAD

**Issue by beaugunderson** [cwhelchel/potamap.ol#6]
Looks to be missing the area definition... I found one here that matches what shows up in OSM very well:

https://www.sciencebase.gov/catalog/item/5d150464e4b0941bde5b7653
https://prd-tnm.s3.amazonaws.com/StagedProducts/Small-scale/data/Boundaries/fedlanp010g.gdb_nt00965.tar.gz

I verified that it opened in QGIS:

<img width="926" alt="89991" src="https://github.com/cwhelchel/potamap.ol/assets/61791/5c359366-8217-4890-9823-f011a94b2636">

**Comment by cwhelchel** [comment]
Thanks for this. I'll look at getting it added.

**Comment by beaugunderson** [comment]
I compared again against what shows in OSM and the OSM boundary does not
have the holes… One of them seems inaccurate but not sure which! The hole-y
version is probably better than nothing, as it will be inaccurate in a safe
direction at least (it will show as not a park when it might be a park).

I wish there was better boundary information available...

**Comment by cwhelchel** [comment]
@beaugunderson yeah there's a fair amount of hole-y lands that I've run across doing this. I feel like maybe its normal in these data sets.
